version: '2'
services:
    cashload-app:
        image: cashload
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cashload-mysql:3306/cashload?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    cashload-mysql:
        extends:
            file: mysql.yml
            service: cashload-mysql
